---
- hosts: localhost
  user: root
  pre_tasks:
    - name: be sure apt cache is updated
      apt: update_cache=yes

  vars:
    #domserver_bucket: domserver-archives
    #domserver_object: domserver-2015-10-09-141110.tar.gz

  tasks:
    - name: install apache2
      apt: pkg={{item}} state=present
      with_items:
        - apache2
        - libapache2-mod-php5

    - name: disable default apache2 site
      file: state=absent path=/etc/apache2/sites-enabled/000-default

    - name: copy deployment script
      copy: src=files/deploy_domserver.sh dest=/root/deploy_domserver.sh mode=0755

    - name: do something with ufw
      ufw: logging=off
      tags: ['domjudge-server', 'ufw']

  handlers:
    - name: reload apache2
      command: /usr/sbin/service apache2 graceful
