---
- hosts: localhost
  user: root
  pre_tasks:
    - name: be sure apt cache is updated
      apt: update_cache=yes

  tasks:
    - name: install dependencies
      apt: pkg={{item}} state=present
      with_items:
        - nginx
        - php5-fpm
        - php5-mysql
        - php5-gd
        - mysql-client-core-5.6
        - zip
        - unzip
        - python-pip

    - name: copy default nginx config
      pip: name=awscli state=present

    - name: copy default nginx config
      copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf

    - name: disable default nginx site
      file: state=absent path=/etc/nginx/sites-enabled/default

    - name: disable default php fpm pool
      file: state=absent path=/etc/php5/fpm/pool.d/www.conf

    - name: set default security/limits.conf
      copy: src=files/limits.conf dest=/etc/security/limits.d/nginx-limits.conf

    - name: set default sysctl stuff
      copy: src=files/sysctl.conf dest=/etc/sysctl.conf

    - name: copy deployment script
      copy: src=files/deploy_domserver.sh dest=/root/deploy_domserver.sh mode=0755

    - name: do something with ufw
      ufw: logging=off
      tags: ['domjudge-server', 'ufw']
